---

# - name: Install software-properties-common in order to manage the repositories that you install software from.
#   apt: name=software-properties-common state=present update_cache=yes

# - name: Add Ansible PPA
#   apt_repository: repo='ppa:ansible/ansible'

- name: Add yum epel
  yum: name='epel-release' state=present

- name: Install Ansible
  yum: name=ansible state=present

- name: Create an Ansible user
  user: name=ansible
        groups=wheel
        generate_ssh_key=yes
        ssh_key_bits=2048
        ssh_key_file=.ssh/id_rsa
        shell=/bin/bash

- name: Enable ansible user to sudo without password
  lineinfile: "dest=/etc/sudoers state=present regexp='^# wheel' insertafter='^## Same thing without a password' line='%wheel ALL=(ALL) NOPASSWD: ALL'"
